[project]
name = "zero-trust-net"
version = "0.1.0"
description = "Zero Trust Architecture Control Plane & Agent"
requires-python = ">=3.10"
dependencies = []

[tool.uv.workspace]
# Khai báo các thành viên trong workspace
members = ["control-plane", "agent"]
