[project]
name = "agent"
version = "0.1.0"
description = "The Muscle of Zero Trust"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.31.0",
    "schedule>=1.2.1",
    "psutil>=5.9.8",
    "netifaces>=0.11.0",
]
